# Base configs
baseurl: "https://symodeling.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photograph of Siyan Zhang"
subtitle: "See the world through my eyes!"
author: "Siyan Zhang"
header:
 title: "Photography"
 subtitle: "by Siyan Zhang"
footer:
 name: "Hey there, my name is Siyan"
 bio: "I am a model and a curator from Shanghai, China. Doing part-time modeling in daily and now learning curating photos."
 github: "Want a website like this for yourself for free? Just <a href=\"symodeling.github.io/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/ram_patra"
